fix typo & remove kubernetes-stub from requirement

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -58,7 +58,7 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       
       - name: Build and push.
-        uses: docker/build-push-actions@v2
+        uses: docker/build-push-action@v2
         with:
           context: ./frontend
           push: true
@@ -88,38 +88,38 @@ jobs:
           push: true
           tags: shp7724/django-k8s-resource-monitor:latest
 
-  deploy:
-    runs-on: ubuntu-latest
-    name: A job to deploy to MicroK8s.
-    steps:
-      - uses: balchua/microk8s-actions@master
-        with:
-          channel: "1.19/stable"
-          addons: '["dns", "storage", "metrics-server"]'
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   name: A job to deploy to MicroK8s.
+  #   steps:
+  #     - uses: balchua/microk8s-actions@master
+  #       with:
+  #         channel: "1.19/stable"
+  #         addons: '["dns", "storage", "metrics-server"]'
 
-      - name: Check User
-        run: |
-          id
-          sg microk8s -c 'microk8s status'
+  #     - name: Check User
+  #       run: |
+  #         id
+  #         sg microk8s -c 'microk8s status'
 
-      - name: Test MicroK8s
-        id: microk8s
-        run: |
-          set -ex
-          kubectl get no
-          kubectl get pods -A -o wide
-          # wait for storage pod to be ready
-          kubectl -n kube-system wait --for=condition=ready pod -l k8s-app=hostpath-provisioner --timeout=60s
-          storage_ready=$?
-          if [ $storage_ready -ne 0 ]; then
-            echo "Error storage not ready."
-            exit $storage_ready
-          fi
-      - name: Test MicroK8s commands
-        id: microk8s-commands
-        run: |
-          set -ex
-          echo "Executing microk8s status using sg command."
-          sg microk8s -c 'microk8s status'
-          echo "Executing microk8s status using sudo command."
-          sudo microk8s status
+  #     - name: Test MicroK8s
+  #       id: microk8s
+  #       run: |
+  #         set -ex
+  #         kubectl get no
+  #         kubectl get pods -A -o wide
+  #         # wait for storage pod to be ready
+  #         kubectl -n kube-system wait --for=condition=ready pod -l k8s-app=hostpath-provisioner --timeout=60s
+  #         storage_ready=$?
+  #         if [ $storage_ready -ne 0 ]; then
+  #           echo "Error storage not ready."
+  #           exit $storage_ready
+  #         fi
+  #     - name: Test MicroK8s commands
+  #       id: microk8s-commands
+  #       run: |
+  #         set -ex
+  #         echo "Executing microk8s status using sg command."
+  #         sg microk8s -c 'microk8s status'
+  #         echo "Executing microk8s status using sudo command."
+  #         sudo microk8s status
